Add bitcoin onion example
Foundation-Devices/tor pull request #53
Opened 2024-09-25 20:54 UTC by sneurlax

- Add Bitcoin onion example.
- Sync `lib/socks_socket.dart` with `cypherstack/tor`.
- Pin `socks5_proxy` to working version in example.

@icota, I also have a Monero onion example ready.  It's similar so I wondered if it should be included.  Let me know if you want that in, as well

2024-09-25 20:55 UTC, sneurlax commented
Looks like
![Screenshot from 2024-09-25 15-54-51](https://github.com/user-attachments/assets/aa7bc15a-f5e8-45be-a567-f82984a623e1)

with this output
```
...
[   +1 ms] flutter: Instance of Tor created!
[+4481 ms] Starting proxy!
[   +2 ms] flutter: Done awaiting; tor should be running
[        ] flutter: Starting tor took 4 seconds. Proxy running on port 16217
[+13304 ms] flutter: responseData: {"jsonrpc":"2.0","result":{"hosts":{"horsey.cryptocowboys.net":{"tcp_port":50001,"ssl_port":50002,"ws_port":50003,"wss_port":50004},"qly7g5n5t3f3h23xvbp44vs6vpmayurno4basuu5rcvrupli7y2jmgid.onion":{"tcp_port":50001,"ws_port":50003}},"pruning":null,"server_version":"ElectrumX 1.16.0","protocol_min":"1.4","protocol_max":"1.4.3","genesis_hash":"000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f","hash_function":"sha256","services":["tcp://horsey.cryptocowboys.net:50001","ssl://horse
...
```

2024-09-26 12:41 UTC, icota requested changes

2024-09-26 12:43 UTC, icota commented
> @icota, I also have a Monero onion example ready. It's similar so I wondered if it should be included. Let me know if you want that in, as well

Of course, why not? Moneranoj are good people

2024-10-03 22:59 UTC, sneurlax commented on lib/socks_socket.dart
> -// SPDX-FileCopyrightText: 2024 Foundation Devices Inc.
Sorry, this was an oversight due to copying and pasting the latest socks_socket.dart from another repo!

2024-10-04 03:47 UTC, sneurlax commented on lib/socks_socket.dart
> -// SPDX-FileCopyrightText: 2024 Foundation Devices Inc.
Ultimately resolved by f3f56097158e6870bac6dc1e9f7f8656b3ceed49 after a squash and force

2024-10-07 05:31 UTC, icota approved these changes

2024-10-07 05:31 UTC, merged